[versions]
kotlin = "2.0.20"
slf4j = "2.0.16"

# testing resources
jUnit = "5.11.3"
strikt = "0.35.1"

[libraries]
strikt-core = { module = "io.strikt:strikt-core", version.ref = "strikt" }
strikt-mockk = { module = "io.strikt:strikt-mockk", version.ref = "strikt" }

junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "jUnit" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "jUnit" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "jUnit" }

slf4j-simple = { module = "org.slf4j:slf4j-simple", version.ref = "slf4j" }

[bundles]
strikt = ["strikt-core", "strikt-mockk"]
junit = ["junit-jupiter-api", "junit-jupiter-params"]

[plugins]
kotlin = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
dokka = { id = "org.jetbrains.dokka", version = "1.9.20" }
